Code Review: Awesome Books complete website
gabrielyea/awesome-books pull request #4
Opened 2021-07-08 18:22 UTC by gabrielyea

## Awesome books: Complete website.
- Added nav bar with working links. :link: 
- Added MenuNavigation class, it handles page navigation. :car: 
- Dynamically assigns links functionality.
- MenuNavigation class can be easily extended to include any number of links and targets.

2021-07-08 20:50 UTC, hemant-soni-vst-au4 requested changes
Hi @gabrielyea and @amiraabouhadid, 

Good job so far! 👍 
You still need to work on some issues to go to the next project, but you are almost there! 

![Alt Text](https://media.giphy.com/media/q6U4fbreC4Neo/giphy.gif)
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Add some hovering effect on the `add` button.

Cheers,
Hemant Soni
Cheers and happy coding 😃

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. You can mention me (@hemant-soni-vst-au4) so I can see your comments and respond.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-08 20:50 UTC, hemant-soni-vst-au4 commented on index.html
> +  </nav>
- [ ] Please try to add the respective link name and logo. Your links are working fine.

![image](https://user-images.githubusercontent.com/53019916/124986981-edb97e80-e059-11eb-86df-ce83a72bfee6.png)

2021-07-08 20:50 UTC, hemant-soni-vst-au4 commented on index.html
> +
- [ ] Please try to add a footer at bottom of the page.

![image](https://user-images.githubusercontent.com/53019916/124987224-3cffaf00-e05a-11eb-9cb6-e28402bc98d0.png)

2021-07-08 20:50 UTC, hemant-soni-vst-au4 commented on css/main.css
> +/* CONTACT */
- [ ] Please try to delete the `comments` in main.css file.

2021-07-08 20:50 UTC, hemant-soni-vst-au4 commented on scripts/menu-navigation.js
> +// Class that handles menu navigation.
- [ ] Kindly delete the `comments` in all files.

2021-07-08 20:50 UTC, hemant-soni-vst-au4 commented on index.html
> +  </nav>
- [ ] As per project requirements Display the current date below the navigation bar. For this requirement, you should use a library - [Luxon](https://moment.github.io/luxon/#/install). I am not able to see the use of Luxon in your project, Please try to fix this issue.
![image](https://user-images.githubusercontent.com/53019916/124988422-97e5d600-e05b-11eb-8d9c-b225c6cd3336.png)

2021-07-08 22:26 UTC, gabrielyea commented on scripts/menu-navigation.js
> +// Class that handles menu navigation.
Hello! this review submission was accidental I am sorry! My partner forgot to push changes! But I'll use this opportunity to ask you:
I thought writing documentation was good practice, why should it be removed from the js files?
Thanks for your input!

2021-07-09 16:32 UTC, Dipeshtwis approved these changes
# Hi @gabrielyea and @amiraabouhadid, 

### Status: Approved ✔️

:+1:  Professional repo, with good commit message and PR title, keep up the good work :muscle:
:+1: Implemented all the required changes. Well Done.

Your project is complete!  There are some optional changes I've suggested to you to make your project best, other than that nothing else to say.
Congratulations! 🎉 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**_check the comments under the review_**


**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
-----

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Dipesh Kumar_**

------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-09 16:32 UTC, Dipeshtwis commented on scripts/main.js
[OPTIONAL]

- I recommend to reset the form after adding book into your list. So that user can easily add another book in the list. Currently after adding the book form looks like this:

![Screenshot from 2021-07-09 21-55-18](https://user-images.githubusercontent.com/22434660/125109606-36784280-e101-11eb-9fcd-06fedc45f9e5.png)

2021-07-09 16:36 UTC, Dipeshtwis commented on scripts/menu-navigation.js
> +// Class that handles menu navigation.
Hello @gabrielyea,

It's good to give comment to understand the code later on as well, but when we're moving code to production the best practice is to remove our comments to make code readable. 

Hope my statement makes sense to you. :smile:

2021-07-09 16:50 UTC, merged